config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  # get 'relationships/create'
  # get 'relationships/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'homes#top'

  resources:books,only:[:new,:create,:index,:show,:destroy,:edit,:update]do
    resource:favorites,only:[:create,:destroy]
    resources:book_comments,only:[:create,:destroy]
  end

  resources :users, only: [:show,:edit,:update,:index]do
      resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
 end
 
  

  get'home/about' =>'homes#about'
  get '/search' => 'search#search'
  # get'users' =>'users#index'
  resources :groups do
    get "join" =>"groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  

  validates :name, uniqueness: true,length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  has_many :group_users
  has_many :groups, through: :group_users
  #ユーザーは多くのグループに属します。それらは、group_usersのテーブルから参照できます
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :update]



  def show
    @user=User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order

    @book=Book.new
  end

  def index
   @users=User.page(params[:page]).reverse_order
   @book=Book.new
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id),notice:'You have updated user successfully.'
    else
      render:edit
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_url(current_user)) unless @user == current_user
  end

  
   private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_show.html.erb
<main>

<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">

<!--ユーザ情報-->
<h2>User info</h2>
<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %>
<table class="table">
 <tbody>
  <tr>
  <th>name</th>
  <th><%= current_user.name %></th>
  </tr>
  <tr>
  <th>introduction</th>
  <th><%= current_user.introduction %></th>
  </tr>
  <tr>
  <th>follows</th><th><%= link_to user_followings_path(current_user.id) do %><%= current_user.followings.count %><% end %></th>
  </tr>
  <tr>
  <th>followes</th><th><%= link_to user_followers_path(current_user.id) do %><%= current_user.followers.count %><% end %></th>
  </tr>
 </tbody>
 </table>



 <%= link_to edit_user_path(current_user),class:'btn btn-outline-secondary btn-block' do %>
 <i class="fas fa-user-cog"></i>
 <% end %>

app/views/users/edit.html.erb
<div class="error" style="color:red; font-size:20px;margin:10px;">
<% if @user.errors.any? %>
<p class="error_title" style="font-size:30px;"><%= @user.errors.count %>errors prohibited this obj from being saved:</p>
<% @user.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
<% end %>
</div>
<main>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">


<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>

  <div class="form-group" style="margin-bottom:20px;">
  <label for="user_name">Name</label>
  <div>
    <%=f.text_field:name,autofocus: true,id:"user_name", placeholder:"name",class:"form-control"%>
  </div>
  </div>

  <div class="form-group" style="margin-bottom:20px;">
  <label for="inputImage">Image</label>
   <div>
     <%= attachment_image_tag @user, :profile_image, :fill, 60, 60 %>
  </div>
  <div>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  </div>
  </div>

  <div class="form-group">
  <label>Introduction</label>
  <div>
    <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Please introduce yourself",class:"form-control"%>
  </div>
  </div>

  <div class="action" style="margin-top:10px;">
  <%= f.submit " Update User " ,class: 'btn btn-secondary'%>
  <% end %></div>


</div>
</div>
</div>
</main>

app/views/users/index.html.erb
<%= render 'users/user_show', users: @users %>

<!--本の新規投稿-->
<%= render 'books/book_new', book: @book %>
<!--テーブル-->
<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
<table class="table table-hover table-inverse">
<thred>
 <tr>
  <th>image</th>
  <th>name</th>
  <th colspan="4"></th>
 </tr>
 </thred>

<tbody>
 <tr>
 <% @users.each do |user| %>
 <td><%= attachment_image_tag user, :profile_image,format:'jpeg',size: "50x50", fallback: "no_image.jpg" %></td>
 <td><%= user.name %></td>
 <td>フォロー数: <%= user.followings.count %></td>
 <td>フォロワー数: <%= user.followers.count %></td>
 <td>
      <% if current_user.id != user.id %>
        <% if current_user.following?(user) %>
        <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :DELETE %>
        <% else %>
        <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
        <% end %>
      <% end %>
    </td>

 <!--フォロー-->


 <!--フォロー-->
 <td><%=link_to "Show",user_path(user.id)  %></td>
 </tr>
 </tbody>
</div>

 <% end %>

 <%= paginate@users %>


<!--%= link_to book_path(book.id) do %> % end %-->
<!--<p>ユーザーネーム：%= book.user.name %></p>-->
</div>
</div>
</main>
</table>

app/views/users/show.html.erb
<main>

<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">

<!--ユーザ情報-->
<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image,:fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %>
<table class="table">
 <tbody>
  <tr>
  <th>name</th>
  <th><%= @user.name %></th>
  </tr>
  <tr>
  <th>introduction</th>
  <th><%=@user.introduction %></th>
  </tr>
  <tr>
  <th>follows</th><th><%= link_to user_followings_path(@user.id) do %><%= @user.followings.count %><%end%></th>
  </tr>
  <tr>
  <th>followes</th><th><%= link_to user_followers_path(@user.id) do %><%= @user.followers.count %><%end%></th>
  </tr>
   </tbody>
 </table>
  

  <% if current_user.id != @user.id %>
   <% if current_user.following?(@user) %>
   <div class="button" style="margin:10px 0;"><%= link_to 'フォローを外す', user_relationships_path(@user.id), method: :DELETE,class:"btn btn-info btn-block" %></div>
        <% else %>
   <div class="button" style="margin:10px 0;"><%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST,class:"btn btn-success btn-block" %></div>
        <% end %>
      <% end %>


<%= link_to edit_user_path(@user),class:'btn btn-outline-secondary btn-block' do %><i class="fas fa-user-cog"></i><% end %>
 <!--% if @user == current_user %>-->
 <!--%= link_to edit_user_path(current_user),class:'btn btn-outline-secondary btn-block' do %>-->
 <!--<i class="fas fa-user-cog"></i>-->
 <!--% end %>-->
 <!--% else %>-->
 <!-- %= link_to user_path(current_user),class:'btn btn-outline-secondary btn-block' do %>-->
 <!--<i class="fas fa-user-cog"></i>-->
 <!--% end %>-->
 <!--% end %>-->



<!--本の新規投稿-->
<%= render 'books/book_new', book: @book %>

<!--投稿している本の情報---->
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
<thred>
 <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
  </tr>
</thred>

<tbody>
<tr>
 <% @books.each do |book| %>

<td><%= link_to user_path(book.user.id) do %>
<%= attachment_image_tag book.user, :profile_image,format: 'jpeg',size: "40x40", fallback: "no_image.jpg" %>
 <% end %></td>


 <!--<td>%= attachment_image_tag @user, :profile_image, format: 'jpeg',size: "50x50",fallback: "no_image.jpg" %></td>-->
<td><%= link_to book_path(book.id) do %><%= book.title %>
<% end %></td>
<td><%= book.body %></td>
<td></td>
<td>コメント数：<%= book.book_comments.count %></td>
</tr>

</tbody>
</div>


 <% end %>

 </div>
 </div>
 </main>
 </table>