config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  # get 'relationships/create'
  # get 'relationships/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'homes#top'

  resources:books,only:[:new,:create,:index,:show,:destroy,:edit,:update]do
    resource:favorites,only:[:create,:destroy]
    resources:book_comments,only:[:create,:destroy]
  end

  resources :users, only: [:show,:edit,:update,:index]do
      resource :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
 end
 
  

  get'home/about' =>'homes#about'
  get '/search' => 'search#search'
  # get'users' =>'users#index'
  resources :groups do
    get "join" =>"groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to:user

validates :title, presence: true
validates :body, presence: true,length:{maximum:200}
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy

 def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
 end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit]

  def new
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
    redirect_to book_path(@book.id),notice:'You have created book successfully.'
    else
    @books=Book.page(params[:page]).reverse_order
    render:index
    end
  end

  def index
    @book=Book.new
    @books=Book.page(params[:page]).reverse_order

  end

  def show
    @books=Book.find(params[:id])
    @book=Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments.order(created_at: :desc)

  end

  def edit
    @book=Book.find(params[:id])
  end


  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id),notice:'You have updated book successfully.'
    else
    render:edit
    end
  end

  def destroy
    @book=Book.find(params[:id])
    if @book.destroy
    redirect_to books_path
    end
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
    redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_new.html.erb
 <h2 class="mt-3">New book</h2>
 <%= form_with model:book,local:true do |f| %>

 <label>Title</label>
 <p><%= f.text_field:title %></p>
 <label>Opinion</label>
 <p><%= f.text_area:body %></p>

<%= f.submit' Create Book ' ,class:'btn btn-success' %>

<% end %>
</div>

app/views/books/edit.html.erb
<div class="error" style="color:red; font-size:20px;margin:10px;">
<% if @book.errors.any? %>
<p class="error_title" style="font-size:30px;"><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
<% end %>
</div>

<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">


<h1>Editing Book</h1>
<%= form_with model:@book, local: true do |f| %>
<div class="form-group" style="margin-bottom:20px;">
<label for="book_title">Title</label>
<div><%=f.text_field:title,autofocus: true,id:"book_title", placeholder:"本のタイトル",class:"form-control"%>
</div>
</div>

<div class="form-group" style="margin-bottom:20px;">
<label for="book_opinion">Opinion</label>
<div><%=f.text_area:body,autofocus: true,id:"book_opinion", placeholder:"最大２００文字までです。",class:"form-control"%>
</div>
</div>

<div class="action" style="margin:20px 0 ;">
<%= f.submit ' Update Book ',class: 'btn btn-success' %>
<% end %></div>

<%= link_to "Show","/books/#{@book.id}"%>|
<%= link_to "Back","/books"%>

</div>
</div>
</div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div class="error" style="color:red; font-size:20px;margin:10px;">
<p class="error_title" style="font-size:30px;"><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
<% end %>
</div>


<!--ユーザー情報-->
<%= render 'users/user_show', users: @users %>



<!--本の新規投稿-->
<h2 class="mt-3">New book</h2>

 <%= form_with model:@book,local:true do |f| %>
 <label>Title</label>
 <p><%= f.text_field:title %></p>
 <label>Opinion</label>
 <p><%= f.text_area:body %></p>

<%= f.submit' Create Book ' ,class:'btn btn-success' %>
<% end %>
</div>


<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
<thred>
 <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
  </tr>
</thred>

<tbody>
<tr>
 <% @books.each do |book| %>
 
<td><%= link_to user_path(book.user.id) do %>
<%= attachment_image_tag book.user, :profile_image,format: 'jpeg',size: "40x40", fallback: "no_image.jpg" %>
 <% end %></td>
 
<td><%= link_to book_path(book.id) do %><%= book.title %></td>
<td><%= book.body %></td>

<!--いいねの数-->
<td id="book_<%=book.id %>"><%= render "favorites/favorites", books: book %></td> 


<td>コメント数：<%= book.book_comments.count %><% end %></td>
</tr>


</tbody>
</div>
<% end %>
 </div>
 </div>
 </main>
 </table>
<%= paginate@books %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
 
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<main>

<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">

 <!--ユーザ情報-->
<h2>User info</h2>
<%= attachment_image_tag @books.user, :profile_image,:fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %>
<table class="table">
 <tbody>
  <tr>
  <th>name</th>
  <th><%= @books.user.name %></th>
  </tr>
  <tr>
  <th>introduction</th>
  <th><%=@books.user.introduction %></th>
  </tr>
 </tbody>
 </table>


 <%= link_to edit_user_path(@books.user.id),class:'btn btn-outline-secondary btn-block' do %><i class="fas fa-user-cog"></i><% end %>


 <!--本の新規投稿-->
<%= render 'books/book_new', book: @book %>



<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table table-hover table-inverse">
<tbody>
  <tr>
  <td>
   <div class="box">
    <%=link_to user_path(@books.user.id) do %><%= attachment_image_tag @user, :profile_image, format: 'jpeg',size: "50x50",fallback: "no_image.jpg" %><% end %>
    <p><%=link_to @books.user.name,user_path(@books.user.id)%></p>
   </div>
   </td>

  <td><%= link_to @books.title,book_path(@books) %></td>
  <td><%= @books.body %></td>

  <!--いいねの数-->
  <td id="book_<%= @books.id %>"><%= render "favorites/favorites", books: @books %></td>


  <!--コメントの数-->
  <td>コメント数：<%= @books.book_comments.count %></td>
   <% if @books.user == current_user %>
  <td class="botton"><%= link_to"Edit",edit_book_path(@books),class:'btn btn-success'%></td>
  <td class="botton"><%= link_to"Destroy",book_path(@books), method: :delete,class:'btn btn-danger'%></td>
  <% end %>
  </tr>
  </tbody>
  </table>
　<div id="comments-area"><%= render "book_comments/comment",books: @books,book_comment: @book_comment %></div>

</div>
</div>
</div>

</main>